# ---
# title: 3mm EPI fMRI
# author: Pierre-Antoine Comby, Alexandre Vignaud, Philippe Ciuciu
# description: This is the configuration used for the scenario 1 of the SNAKE Paper
# ---

defaults:
  - base_config
  - handlers:
    - activation-block
  - sampler:
    - epi-3d
  - reconstructors: adjoint
  - _self_

cache_dir: ${oc.env:PWD}/cache
result_dir: results/scenario1/
filename:  ${oc.env:PWD}/scenario1_${engine.model}_${engine.snr}.mrd

sim_conf:
  max_sim_time: 360
  seq: {TR: 2000, TE: 40, FA: 73}
  hardware:
    n_coils: 8
  fov:
    res_mm: [3, 3, 3]
    size: [181, 217, 3]
    offset: [-90, -125, 10]

phantom:
  name: brainweb
  sub_id: 4
  tissue_ignore: ["bck"]
  tissue_file: "tissue_7T"
handlers:
  activation-block:
    event_name: block_on
    block_on: 20 # seconds
    block_off: 20 #seconds
    duration: 360 # seconds
    delta_r2s: 1000 # millisecond^-1
sampler:
  epi-3d:
    acsz: 0.1
    accelz: 1
    orderz: TOP_DOWN

engine:
  n_jobs: 10
  chunk_size: 60
  model: "simple"
  snr: 10000
  slice_2d: True

reconstructors:
  adjoint: {}



hydra:
  job:
    chdir: true

  run:
    dir: ${result_dir}/outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${result_dir}/multirun/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}

  callbacks:
    # gather_files:
    #   _target_: hydra_callbacks.MultiRunGatherer
    #   aggregator:
    #     _partial_: true
    #     _target_: snkf.cli.utils.aggregate_results

    latest_run:
      _target_: hydra_callbacks.LatestRunLink
      run_base_dir:  ${result_dir}/outputs
      multirun_base_dir:  ${result_dir}/multirun
