name: deploy-docs

# Only run this when the master branch changes
on:
  push:
    branches:
    - main
    - master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  create_venv: "python -m venv $RUNNER_WORKSPACE/venv"
  activate_venv: "source $RUNNER_WORKSPACE/venv/bin/activate"
  setup_cuda: "export CUDA_BIN_PATH=/usr/local/cuda-12.1/;export PATH=/usr/local/cuda-12.1/bin/:${PATH};export LD_LIBRARY_PATH=/usr/local/cuda-12.1/lib64/:${LD_LIBRARY_PATH}"

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: gpu
    steps:
    - uses: actions/checkout@v4

    # Install dependencies
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: pip
    - name: Restore cached brainweb-dl directory
      uses: actions/cache/restore@v4
      id: cache-restore
      with:
        path: ~/.cache/brainweb
        key: ${{ runner.os }}-Brainweb

    - name: Install dependencies
      run: |
        ${{ env.create_venv }}
        ${{ env.setup_cuda }}
        ${{ env.activate_venv }}
        pip install mri-nufft[finufft,cufinufft] ipywidgets
        pip install -e .[doc,toolkit]
        pip install git+https://github.com/mind-inria/mri-nufft

    # Build the book
    - name: Build the book
      continue-on-error: true
      run: |
        ${{ env.activate_venv }}
        python -m sphinx docs docs_build

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'docs_build/'

    - name: Cache brainweb-dl directory
      uses: actions/cache/save@v4
      if: ${{ steps.cache-restore.outputs.cache-hit != 'true' }}
      with:
        path: ~/.cache/brainweb
        key: ${{ runner.os }}-Brainweb

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
